# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  fileSystems = {
    # The main drive is configured via the SD image installer

    # USB drive labelled 'backup'
    "/backup" = {
      device = "/dev/disk/by-label/backup";
      fsType = "ext4";
    };
  };

  # !!! Adding a swap file is optional, but strongly recommended!
  swapDevices = [{ device = "/swapfile"; size = 1024; }];

  hardware.enableRedistributableFirmware = true;
}
